import { Metadata } from "next";
import SchemaOrg from "@/components/seo/SchemaOrg";
import Link from "next/link";
import { Handshake, TrendingUp, Users, ArrowRight } from "lucide-react";

export const metadata: Metadata = {
  title: "100 JILI Affiliate Program | Earn Passive Income Weekly",
  description: "Join the 100 JILI Affiliate Program and earn industry-leading commissions. Turn your network into a lucrative revenue stream with weekly payouts.",
};

export default function Hub8PillarPage() {
  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://100-jili.ph/"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "100 JILI Affiliate",
        "item": "https://100-jili.ph/100-jili-affiliate"
      }
    ]
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "How much can I earn as a 100 JILI Affiliate?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Your earning potential is unlimited. We offer an aggressive tiered commission structure where top-performing agents earn over 50% revenue share."
        }
      },
      {
        "@type": "Question",
        "name": "Is it free to join the affiliate program?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes, joining the 100 JILI Affiliate Program is 100% free. We provide you with the tracking links and marketing materials at no cost."
        }
      }
    ]
  };

  return (
    <>
      <SchemaOrg schema={breadcrumbSchema} />
      <SchemaOrg schema={faqSchema} />
      
      <section className="bg-[var(--color-brand-midnight)] py-20 border-b border-[var(--color-brand-light-navy)]">
        <div className="container mx-auto px-4 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-[var(--color-brand-navy)] border border-[var(--color-brand-neon-jade)] mb-6">
            <Handshake className="w-8 h-8 text-[var(--color-brand-neon-jade)]" />
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6">
            100 JILI Affiliate Program
          </h1>
          <p className="text-lg md:text-xl text-[var(--color-brand-slate)] mb-10 max-w-3xl mx-auto">
            Partner with the fastest-growing online casino in the Philippines. Turn your social media influence, 
            website traffic, and personal network into a continuous stream of passive income.
          </p>
          <Link href="/100-jili-agent-login" className="inline-flex items-center gap-2 px-8 py-4 bg-[var(--color-brand-neon-jade)] text-[var(--color-brand-midnight)] font-bold rounded-lg text-lg hover:bg-[var(--color-brand-dark-jade)] transition-colors shadow-[0_0_20px_rgba(0,255,136,0.4)]">
            Become an Agent Today <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      <section className="py-16">
        <div className="container mx-auto px-4 grid grid-cols-1 lg:grid-cols-3 gap-12">
          <article className="lg:col-span-2 prose prose-invert max-w-none text-[var(--color-brand-slate)]">
            <h2 className="text-3xl font-bold text-white mt-0">Why Partner With Us?</h2>
            <p className="text-lg leading-relaxed">
              The <strong>100 JILI Affiliate Program</strong> is designed to be the most lucrative and transparent 
              partnership scheme in the iGaming industry. We provide our agents with high conversion rates, unparalleled 
              player retention, and a guarantee of on-time weekly payouts.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-10">
              <div className="bg-[var(--color-brand-navy)] border border-[var(--color-brand-light-navy)] p-6 rounded-xl">
                <TrendingUp className="w-10 h-10 text-[var(--color-brand-neon-jade)] mb-4" />
                <h3 className="text-xl font-bold text-white mt-0 mb-2">High Conversion Rates</h3>
                <p className="text-sm mb-0">Our premium brand reputation and aggressive welcome bonuses make player acquisition effortless.</p>
              </div>
              <div className="bg-[var(--color-brand-navy)] border border-[var(--color-brand-light-navy)] p-6 rounded-xl">
                <Users className="w-10 h-10 text-blue-400 mb-4" />
                <h3 className="text-xl font-bold text-white mt-0 mb-2">Lifetime Revenue Share</h3>
                <p className="text-sm mb-0">You earn a percentage of the net revenue generated by your referrals for as long as they play.</p>
              </div>
            </div>

            <h3 className="text-2xl font-bold text-white">How the Program Works</h3>
            <ol className="list-decimal pl-6 space-y-4">
              <li><strong>Register:</strong> Sign up for an agent account. Approval is fast and free.</li>
              <li><strong>Promote:</strong> Use your unique referral link to invite players via Facebook, Telegram, TikTok, or your own website.</li>
              <li><strong>Track:</strong> Monitor your clicks, sign-ups, and generated revenue in real-time through the Agent Dashboard.</li>
              <li><strong>Earn:</strong> Receive your commission payouts directly to your GCash or bank account every week.</li>
            </ol>
            
            <h2 className="text-3xl font-bold text-white mt-12 mb-6">Frequently Asked Questions</h2>
            <div className="space-y-6">
              <div>
                <h4 className="text-xl font-bold text-white mb-2">How much can I earn as a 100 JILI Affiliate?</h4>
                <p>Your earning potential is unlimited. We offer an aggressive tiered commission structure where top-performing agents earn over 50% revenue share.</p>
              </div>
              <div>
                <h4 className="text-xl font-bold text-white mb-2">Is it free to join the affiliate program?</h4>
                <p>Yes, joining the 100 JILI Affiliate Program is 100% free. We provide you with the tracking links and marketing materials at no cost.</p>
              </div>
            </div>
          </article>

          <aside className="lg:col-span-1">
            <div className="sticky top-24 bg-[var(--color-brand-navy)] border border-[var(--color-brand-light-navy)] p-6 rounded-2xl">
              <h3 className="text-xl font-bold text-white mb-6">Affiliate Resources</h3>
              <ul className="space-y-4">
                <li>
                  <Link href="/100-jili-commission-rate" className="block p-4 rounded-lg border border-[var(--color-brand-light-navy)] hover:border-[var(--color-brand-neon-jade)] hover:bg-[var(--color-brand-midnight)] transition-all">
                    <span className="block font-bold text-white mb-1">Commission Rates</span>
                    <span className="text-sm text-[var(--color-brand-slate)]">View our tiered revenue share structure.</span>
                  </Link>
                </li>
                <li>
                  <Link href="/100-jili-agent-login" className="block p-4 rounded-lg border border-[var(--color-brand-light-navy)] hover:border-[var(--color-brand-neon-jade)] hover:bg-[var(--color-brand-midnight)] transition-all">
                    <span className="block font-bold text-white mb-1">Agent Login Portal</span>
                    <span className="text-sm text-[var(--color-brand-slate)]">Access your tracking dashboard.</span>
                  </Link>
                </li>
                <li>
                  <Link href="/100-jili-marketing-tools" className="block p-4 rounded-lg border border-[var(--color-brand-light-navy)] hover:border-[var(--color-brand-neon-jade)] hover:bg-[var(--color-brand-midnight)] transition-all">
                    <span className="block font-bold text-white mb-1">Marketing Tools</span>
                    <span className="text-sm text-[var(--color-brand-slate)]">Download banners and promotional copy.</span>
                  </Link>
                </li>
              </ul>
            </div>
          </aside>
        </div>
      </section>
    </>
  );
}
